# Generated by Django 5.2.8 on 2025-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(),
        ),
    ]
